In [3]:
import numpy as np
print(np.__doc__)



NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularl

In [32]:
import sys


num= 10000
#a = np.array([1,2,3,4,5,1.1111111111111,2,3,5.1,8,9,0,1,2,1,2,3,4,5,1.1,2,3,5.1,8,9,0,1,2,1,2,3,4,5,1.1,2,3,5.1,8,9,0,1,2,1,2,3,4,5,1.1,2,3,5.1,8,9,0,1,2])
a = np.arange(num)
l1 = list(range(num))
#l1 = [1,2,3,4,5,1.1111111111111,2,3,5.1,8,9,0,1,2,1,2,3,4,5,1.1,2,3,5.1,8,9,0,1,2,1,2,3,4,5,1.1,2,3,5.1,8,9,0,1,2,1,2,3,4,5,1.1,2,3,5.1,8,9,0,1,2]
#Size of list is more compared to numpy array.
print(sys.getsizeof(a))
print(sys.getsizeof(l1))



80096
90112


In [13]:
a = np.array([1,2,3,4,5,1.1])
print(a.dtype)
l1 = [1,2,3,4,5,1.1]
print(type(l1[0]))
print(type(l1[-1]))

float64
<class 'int'>
<class 'float'>


In [3]:
import numpy as np
import sys
import datetime

num= 10000000
l1 = list(range(num))
l2 = list(range(num))

start = datetime.datetime.now()
l3 = list(map(lambda x,y:x+y, l1,l2))
end = datetime.datetime.now()
print(end-start)


a1 = np.array(l1)
a2 = np.array(l2)

start = datetime.datetime.now()
a3 = a1+a2
end = datetime.datetime.now()
print(end-start)

0:00:01.695333
0:00:00.129754


In [10]:
#Mathematical operations
a1 = np.arange(1,10)
a2 = np.arange(1,10)
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1%a2)

for element in a1:
    print(element)

[ 2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0]
[ 1  4  9 16 25 36 49 64 81]
[0 0 0 0 0 0 0 0 0]
1
2
3
4
5
6
7
8
9


In [17]:
#Two dimensional arrays
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1%a2)
print(a1@a2)#Matrix multiplication;
print("Transpose=", np.transpose(a1))
print("Transpose=", np.invert(a1))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
Transpose= [[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose= [[ -2  -3  -4]
 [ -5  -6  -7]
 [ -8  -9 -10]]


In [20]:
z1 = np.zeros(10)
print(z1)
o1 = np.ones(10)
print(o1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [25]:
z1 = np.zeros(10)
z2 = z1.reshape((5,2))
print(z2)
print(z1)
o1 = np.ones(10)
print(o1)


SyntaxError: invalid syntax (<ipython-input-25-7d5c496e000e>, line 8)

In [11]:
import numpy as np
import sys
np.random.seed = 123
array = np.random.randint(0,100,10)
print(np.random.seed)
print(array)

print(array.dtype)
print(array.size)
print(array.nbytes)#Memory used to store the numbers
print(sys.getsizeof(array))#Memory used to store entire object
print(array.shape)
print(array.ndim)
print(array.sum())
print(array.mean())

123
[80 68 56 53 52 75  8 93  2 71]
int64
10
80
176
(10,)
1
558
55.8


In [12]:
a = np.array([[1, 2],[4,5]])
b = np.array([3,5])

np.linalg.solve(a,b)

array([-1.66666667,  2.33333333])