In [24]:
import os

os.uname()
'''
fork
wait waitpid
kill
pid 
ppid
'''
#print(os.environ)
print(os.environ["USER"])
print("Pid = ", os.getpid())
print("Pid = ", os.getppid())
pwd = os.getcwd()
print("Cwd = ", os.getcwd())
os.chdir("../")
print("Cwd = ", os.getcwd())
os.chdir(pwd)
print("Cwd = ", os.getcwd())





kamalmukiri
Pid =  54238
Pid =  54158
Cwd =  /Users/kamalmukiri/Documents/AptComputingAcademy/GreatLearning
Cwd =  /Users/kamalmukiri/Documents/AptComputingAcademy
Cwd =  /Users/kamalmukiri/Documents/AptComputingAcademy/GreatLearning


In [3]:
import os
list_of_files = os.listdir()
#print(list_of_files)
os.chdir("/Users/kamalmukiri/Documents/AptComputingAcademy")
for cur_dir, dirs, files in os.walk("./"):
#     print("cur_dir = ",cur_dir)
#     print("dirs = ", dirs)
#     print("files = ", files)
    for file in files:
        if ".cpp" in file and "FindNearest" in file:
            print(file)
            print(cur_dir)
#         try:
#             if os.stat(file).st_size >= 1024*500:
#                 print(file, cur_dir)
#         except:
#             pass

FindNearestCity.cpp
./Cpp/Classes/regex/gps/class_file


# Tasks for the day:
   - 1) Hands on "numpy" module
   - 2) Prove that "numpy" is better than array
   - 3) Use "matplotlib" to see the fata visually
   - 4) Try more number of operations on arrays/matrices
   - 5) Try more functions in "numpy"

In [69]:
import numpy as np
a = np.array([1.1,2,3,4])
print(a.dtype)

a = np.array([1.1+1j,2,3,4])
print(a)
print(a.dtype)

a = np.array([1,2,3,4])
print(a)
print(a.dtype)

float64
[1.1+1.j 2. +0.j 3. +0.j 4. +0.j]
complex128
[1 2 3 4]
int64


In [73]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(type(a))
print(a+b)
print(a*b)
print(a-b)





<class 'numpy.ndarray'>
[2 4 6 8]
[ 1  4  9 16]
[0 0 0 0]


# Numpy (Numerial Python package):

# What is numpy: 
   - extension package to Python for multi-dimensional arrays
   - efficient hardware implementation: Faster and consumes less memory
   - designed for scientific computation
   - Does *array oriented computing *
   
### Note: It is useful for integer/float/complex numbers

## 1)  Importing the numpy package and an example:


## Note : Arrays can store elemements of the same type


In [74]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(type(a))
print(a+b)
print(a*b)
print(a-b)




<class 'numpy.ndarray'>
[2 4 6 8]
[ 1  4  9 16]
[0 0 0 0]


# Advantages of array in numpy 
1. Uses less space and its faster in computation 


2. Numpy arrays are faster than the python lists 


In [1]:
import numpy as np
import time
no_element = 10000000
list1 = list(range(no_element))
list2 = list(range(no_element))

now = time.time()
list3 = []
for i in range(no_element):
    list3.append(list1[i]+list2[i])
print("Time taken using lists= ", time.time()-now)

now = time.time()
a = np.arange(no_element)
b = np.arange(no_element)
c = a+b
print("Time taken using np = ", time.time()-now)


Time taken using lists=  4.056675910949707
Time taken using np =  0.17153215408325195


# 2)Creating a 2 dimensional array 


# 2.1)Reshaping an array 


# 2.2)Creating a zero value array 


# 2.3) Understanding the ravel function,its used to convert an N dimensional array into a 1 dimensional array 


# 2.4)Finding out the min and max element from an array 


# In class lab exercise  : 
Program a code snippet develop a custom user defined function to find out the min and max element from an 2 by 3 array or elements 
as shown below 

1 2
3 4
5 6 

Hint : U may use the ravel function to flatten it out and then work on finding the min and max elements from the array 
Note : U are not supposed to use the min or max built in function 


# 3)Operations on arrays (Addition, subtraction and multiplication is possible)


# Slicing python lists 


In [22]:
l = [1,2,3,4,5]
l[2:4]


[3, 4]

# Similar kind of slicing is possible on Python arrays 


In [5]:
d2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(d2)

print(d2[0:,0]) #This would print the element from 0th row and 0th column i.e 1 
print(d2[1,0]) #This would print the element from 0th row and 0th column i.e 5 


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 4 7]
4


# q)Iterating the array using for loops 

1 2 3
4 5 6
7 8 9

The array d2 contains the above elements

In [ ]:
for row in d2:
 print(row) 


# q)Conditional statements on arrays 


# In class lab exercise : 
To create an array with 100 elements (M,N is 5,10) anf filter only those elements between than 75 and 100 and create a new array with 5 rows and 5 cols 


# q)Replacing all the elements of an array which is greater than 4 with zero 


In [6]:
ca = np.arange(9).reshape(3,3)
con = ca > 4
ca[con]=0




# q)Taking a 1 dimensional array and reshaping it to a 2 dimensional array 
