# INCLASS NOTEBOOKS

## Importing the `numpy package `

**What is Numpy.**

NumPy refers to Numerical Python and it is an open source library in Python that aids in mathematical ,numerical calculations and computations , scientific, engineering, and data science programming. 

NumPy is an most essential library to perform mathematical and statistical operations. It works perfectly well for multi-dimensional arrays and matrices multiplication.

Numpy is memory efficiency, meaning it can handle the vast amount of data more accessible than any other library. Besides, NumPy is very convenient to work with, especially for matrix multiplication and reshaping and more helpful in machine learning.

Numpy makes the work simpler by doing the complex numerical computations in background.

In [2]:
import numpy as np

list_l =[[12,34,55,],[66,45,77],[45,77,88]]
np.array(list_l)


array([[12, 34, 55],
       [66, 45, 77],
       [45, 77, 88]])

## What is an Array.

An array is a special variable, which can hold more than one value at a time.

## How do we construct an `array`.

In [2]:
myarr = np.array([1,2,3,4,5])
print(myarr)

[1 2 3 4 5]


In [3]:
type(myarr)

numpy.ndarray

## Note : Arrays can store elements of the same `type`.


In [11]:
a = np.array([1,2,3,'string',{1:"one"},[]])
print(a)
print(a.dtype)
print(a[0])



[1 2 3 'string' {1: 'one'} list([])]
object
1


## Advantages of array in `numpy`. 
Uses less space and its faster in computation 


## Lets check the size of an integer `type` in Python. 

In [15]:
import sys 
b  = 10
print(sys.getsizeof(b))#Return the size of object in bytes.
print(b.bit_length())

28
4


## Lets check the `size` of an empty list in Python.

In [12]:
myl = []
sys.getsizeof(myl)


NameError: name 'sys' is not defined

## Lets add an item to the list and `check the size `.


In [43]:
myl = [1,2,9,100]
sys.getsizeof(myl)

96

## Note : Every item in the list would occupy `8 bytes `.

## Let us create a `list of 100 elements`. 

In [44]:
myl=list(range(1,100))
print(myl)
print(sys.getsizeof(myl[0]))
type(myl)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
28


list

## Lets now `check the size` of the entire  list 


In [19]:
size_l = sys.getsizeof((myl[1]))*len(myl)
print(size_l)


2772


## Note : getsizeof(myl[1]) would give the size of one element of the list in bytes 



## Now lets create an array of `100 elements` and `check the size of the array`. 


In [35]:
myar = np.array([1,2,3, 'helo'])
myar = myar*myar*myar*myar*myar*myar*myar*myar*myar
print(myar)
print(myar.itemsize)


TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U21') dtype('<U21') dtype('<U21')

## Lets check How to find out the `count of number of elements` in an array


In [0]:
myar.size


100

##  Lets Check How to find the `size (memory occupied) by every item in an array`. 


In [0]:
print(myar.itemsize)


8


## Now we need to `multiple the length of the array` with the memory occupied  by each                        array element to get the total memory occupied by the entire array elements. 



In [45]:
size_a =  (myar.size)*(myar.itemsize)
print(size_a)


400


## Let us Find How to verify that numpy arrays are `faster` than the python lists 


In [27]:
import time
import numpy as np 

num = 10000000
count = num
l1=list(range(count))
l2=list(range(count))

start=time.time()
list3 = [l1[i]+l2[i] for i in range(num)]
end=time.time()
elapsed = 1000*(end-start)
print("List addition time is ",elapsed)

a1 = np.arange(count)
a2 = np.arange(count)
start=time.time()
a3=a1+a2
end=time.time()
elapsed = 1000*(end-start)
print("Numpy Array addition time is ",elapsed)


List addition time is  2665.288209915161
Numpy Array addition time is  93.38998794555664


In [39]:
import sys
import numpy as np
list1 = [1,3,7,100,4,6,10,45,3,6,8,99,87]
print("Size taken by list = ", sys.getsizeof(list1))

a = np.array([1,3,7,100,4,6,10,45,3,6,8,99,87],dtype=np.int8)
print("Size taken by numpy array = ", sys.getsizeof(a))

a = np.array([1,3,7,100,4,6,10,45,3,6,8,99,87],dtype=np.int16)
print("Size taken by numpy array = ", sys.getsizeof(a))

a = np.array([1,3,7,100,4,6,10,45,3,6,8,99,87],dtype=np.int32)
print("Size taken by numpy array = ", sys.getsizeof(a))



Size taken by list =  168
Size taken by numpy array =  109
Size taken by numpy array =  122
Size taken by numpy array =  148


## Lets Create a `2 dimensional array`. 


In [48]:
import numpy as np 
a = np.array([[1,2],[3,4]])
print(a)
a.ndim #The ndim will print the dimensionality of the array i.e 1 dimentional or 2 dimensional 


[[1 2]
 [3 4]]


2

## Lets Check How to `count the number of elements` in any array .


In [8]:
print(a.size) # print the size


print("shape =",a.shape) # would print how many rows and cols are there in the array 



6
shape = (3, 2)


## Lets see another example of using the `shape function`.

In [50]:
a=np.array([[1,2],[3,4],[5,6]])
a.shape  # would print how many rows and cols are there in the array  

(3, 2)

## `Reshaping` an array 


In [39]:
b = a.reshape((2,3))
b.shape
print(b)

b.reshape((1,6))

[[1 2 3]
 ['string' {1: 'one'} list([])]]


array([[1, 2, 3, 'string', {1: 'one'}, list([])]], dtype=object)

## Let see how to `Create a zero value` array .


In [42]:
a = np.zeros( (2,3) )   #will result in creating a 2 row and 3 col array, filled with zeroes 
print(a)

b = np.ones((2,3)) #This will create an array with value 1's 
print(b)

c = np.zeros(10)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Lets `Check about arange function` to create arrays .


In [0]:
a = np.arange(5)
print(a)


[0 1 2 3 4]


## Let us Understand about the `ravel function`,its used to convert an `N dimensional array` into a `1 dimensional array `.


In [43]:
b=np.array([[1,2],[3,4]])
a = b.ravel
print(a)
type(a)

<built-in method ravel of numpy.ndarray object at 0x121096210>


builtin_function_or_method

## Let us Find out the `minimum` and `maximum` element from an array 


In [13]:
b.min() # This will retrive the minimum element value from the array


1

In [15]:
b.max() # This will retrive the maximum element value from the array


4

## Lets see how to check `variance` ,`standard deviation`,`mean` of an array.

In [47]:
x=np.array([[1,2],[3,4],[5,6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

**What is Variance.**

Variance measures how far a data is spread out. The technical definition is “The average of the squared differences from the mean,” but all it really does is to give you a very general idea of the spread of your data. A value of zero means that there is no variability; All the numbers in the data set are the same.

For Example :-

The data set 12, 12, 12, 12, 12 has a var. of zero (the numbers are identical). 

The data set 12, 12, 12, 12, 13 has a var. of 0.167; a small change in the numbers equals a very small var.

The data set 12, 12, 12, 12, 13,013 has a var. of 28171000; a large change in the numbers equals a very large number.

In [48]:
x.var() # Display the variance


a = np.array([5,8,0,1,4,-1,-90])
print(a.var())

1063.673469387755


**what is standard deviation.**

The square root of the variance is the standard deviation. While var. gives you a rough idea of spread, the standard deviation is more concrete, giving you exact distances from the mean.

In [38]:
x.std() # Display the standard deviation

1.707825127659933

In [39]:
x.mean() # Display the mean/average

3.5

In [76]:
a= np.array(["hello world","hel world"])
print(type(a[0]))
print(sys.getsizeof(a[1]))

b = list(range(10000))
print(sys.getsizeof(b))



<class 'numpy.str_'>
90
90112


## Lets see how could we perform Operations on arrays (Addition, subtraction and multiplication is possible)


In [17]:
a=np.ones((2,2))
b=np.ones((2,2))
print(a)
print(b)    # this will print the 2 rows 2 columns filled with ones 

[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]


In [18]:
c = a+b
d = a-b
e = a*b
print("addition result follows\n\n:",c)
print("subtraction result follows\n \n :",d)
print("multiplication result follows\n \n :",e)


addition result follows

: [[2. 2.]
 [2. 2.]]
subtraction result follows
 
 : [[0. 0.]
 [0. 0.]]
multiplication result follows
 
 : [[1. 1.]
 [1. 1.]]


## `Slicing` python lists 


In [0]:
l = [1,2,3,4,5]
l[2:4]


[3, 4]

## Lets check how we can perform Similar kind of slicing on Python arrays 


In [84]:
d2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(d2)

a = d2[:,2]
print(a)
print(type(a))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6 9]
<class 'numpy.ndarray'>


In [78]:
print(d2[0,0]) # This would print the element from 1st row and 1st column i.e 1 
print(d2[1,1]) # This would print the element from 2nd row and 2nd column i.e 5 

1
5



## How to interpret the below statement with respect to the ` Above 3 by 3 array`.



In [22]:
print(d2[0:2,2]) #would print [3 6] 
# [0:2,2] would translate to [(0,1),2] i.e to print the row 1 and row 2 elements of column 2 which is 3,6


[3 6]


In [24]:
print(d2[:,0:2]) # Print all the row elements from col 1 and col 2


[[1 2]
 [4 5]
 [7 8]]


## How do we  iterate the array using for loops 

1 2 3

4 5 6

7 8 9

The array d2 contains the above elements

In [25]:
for row in d2:
    print(row) 


[1 2 3]
[4 5 6]
[7 8 9]


## Lets see the `Conditional statements` on arrays 


In [0]:
ca = np.arange(9).reshape(3,3)
print("The original array is \n" ,ca)

con = ca > 5 

print(" \nThe boolean array after the conditional statement is applied \n")
print(con)

ca[con] # The boolean TRUE/FALSE array is now the index and print only the numbers satisfying the the > 5 condition 


The original array is 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
 
The boolean array after the conditional statement is applied 

[[False False False]
 [False False False]
 [ True  True  True]]


array([6, 7, 8])

## --) Lets see how to `Replace` all the elements of an array which is greater than 4 with zero 


In [0]:
ca = np.arange(9).reshape(3,3)
print("The original array is : \n", ca)

con = ca > 4
ca[con]=0
print("\n",ca) 



The original array is : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[0 1 2]
 [3 4 0]
 [0 0 0]]


## Lets Take a 1 dimensional array and `reshape` it to a 2 dimensional array. 


In [4]:
newa = np.arange(10).reshape(2,5)
newb = np.arange(10,20).reshape(2,5)

print(newa)
print(newb)



[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


## Lets us understand `stacking` operations on an array 


In [5]:
newc=np.vstack((newa,newb))  # vstack is for vertical stacking of arrays 

print(newc)
type(newc)



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


numpy.ndarray

In [28]:
newc=np.hstack((newa,newb))  # hstack is for Horizontal stacking of array

print(newc)
type(newc)


[[ 0  1  2  3  4 10 11 12 13 14]
 [ 5  6  7  8  9 15 16 17 18 19]]


numpy.ndarray

## Lets see how can we `split` a large arrays into smaller arrays 


In [87]:
biga = np.arange(60).reshape(6,10)
print(biga)
biga.shape

sma = np.hsplit(biga,2)  #  sma is a list consisting of 3 smaller arrays 
print(sma[0])
print(sma[1])



[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [50 51 52 53 54]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]
 [35 36 37 38 39]
 [45 46 47 48 49]
 [55 56 57 58 59]]


In [90]:
a = np.vsplit(biga,3)
print(a[0])
print(a[1])
print(a[2])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
[[40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]


In [93]:
b = np.hsplit(biga,2)

sys.getsizeof

---------------------

# ----------------------------------Happy Learning------------------------------------------

--------------